# Generated by Django 3.2.8 on 2022-10-02 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
